"""rename body to content

Revision ID: f1822f9b520f
Revises: 3ecf8ffaa29f
Create Date: 2026-05-15 11:10:56.222296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1822f9b520f'
down_revision: Union[str, Sequence[str], None] = '3ecf8ffaa29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
